"""
Django settings for sistema project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants
import pymysql
pymysql.install_as_MySQLdb()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'default-secret-key')
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'productos',
    'inventario',
    'proveedores',
    'widget_tweaks',
    'sistema',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
    'axes',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',   # ← 1°
    'django.contrib.messages.middleware.MessageMiddleware',      # ← 2° (OBLIGATORIO aquí)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # TUS MIDDLEWARES PERSONALIZADOS VAN DESPUÉS:
    'sistema.middleware.CurrentUserMiddleware',        # ← AHORA SÍ FUNCIONA
    'axes.middleware.AxesMiddleware',
    'usuarios.middleware.NoCacheAuthenticatedMiddleware',  # si lo tienes
    'sistema.middleware.ForzarCambioClaveMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # ← AGREGAR PRIMERO
    'django.contrib.auth.backends.ModelBackend',
]

# Configuración de bloqueo
AXES_FAILURE_LIMIT = 5  # Máximo 5 intentos fallidos
AXES_COOLOFF_TIME = timedelta(seconds=30)   # Bloqueo por 1 hora (en horas)
AXES_RESET_ON_SUCCESS = True  # Resetear contador tras login exitoso
AXES_LOCKOUT_TEMPLATE = 'usuarios/account_locked.html'  # Usa mensaje de error en el form
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_ENABLE_ACCESS_FAILURE_LOG = True
AXES_VERBOSE = True  # Logs detallados
AXES_USERNAME_FIELD_LENGTH = 150
AXES_IP_ADDRESS_FIELD_LENGTH = 45
AXES_ENABLE_ACCESS_LOG = True
# Mensaje de bloqueo personalizado
AXES_COOLOFF_MESSAGE = "Cuenta temporalmente bloqueada por intentos fallidos. Intenta nuevamente en {cooloff_time}."

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}
ROOT_URLCONF = 'sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'sistema' / 'templates'],  # <--- Esto le dice a Django dónde buscar los templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

ENGINE = os.getenv("DB_ENGINE", "sqlite")

if ENGINE == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "ec2-52-203-115-90.compute-1.amazonaws.com"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4",
                        "ssl": {"ca": "/etc/ssl/certs/aws-rds/rds-combined-ca-bundle.pem"}},
        }
    }
else:  # SQLite por defecto
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv("DB_NAME", "dulceria_lilis.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Directorio para tus archivos estáticos durante desarrollo
STATIC_ROOT = BASE_DIR / 'staticfiles'    # Directorio donde se recopilarán los archivos para producción


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'usuarios:login'


SESSION_COOKIE_AGE = 60 * 60 * 2

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_SAVE_EVERY_REQUEST = False

SESSION_COOKIE_SECURE = False

SESSION_COOKIE_SAME_SITE = 'Lax'

MESSAGE_TAGS = {
    constants.DEBUG: 'secondary',
    constants.INFO: 'info',
    constants.SUCCESS: 'success',
    constants.WARNING: 'warning',
    constants.ERROR: 'danger',
}
#email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yearshono@gmail.com'           # Tu cuenta de Gmail 
EMAIL_HOST_PASSWORD = 'xdeaykdeezoyxrxq'          # Tu contraseña de aplicación 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
