# Generated by Django 5.2.5 on 2025-11-10 07:02

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
