# Generated by Django 5.2.5 on 2025-11-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sesiones',
            field=models.PositiveIntegerField(default=0, verbose_name='Sesiones'),
        ),
    ]
