# Generated by Django 5.2.5 on 2025-11-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sesiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, default='Usuario', max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
