# Generated by Django 5.2.5 on 2025-11-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=191, null=True, unique=True, verbose_name='Email'),
        ),
    ]
