# Generated by Django 5.2.5 on 2025-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=True, help_text='Indica si el usuario debe cambiar su clave en el próximo login'),
        ),
    ]
