# Generated by Django 5.2.5 on 2025-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_debe_cambiar_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su clave en el próximo login'),
        ),
    ]
