# Generated by Django 5.2.5 on 2025-11-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_grafica', 'Puede ver la gráfica'), ('ver_actividad', 'Puede ver la actividad')],
                'managed': False,
            },
        ),
    ]
