# Generated by Django 5.2.8 on 2025-11-10 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('proveedores', '0002_alter_proveedor_email_alter_proveedor_sitio_web'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor'),
        ),
    ]
