# Generated by Django 5.2.5 on 2025-11-18 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
        migrations.AddField(
            model_name='lote',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
    ]
