# Generated by Django 5.2.5 on 2025-10-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(default='Chile', max_length=64)),
                ('condiciones_pago', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lead_time_dias', models.IntegerField(default=7)),
                ('min_lote', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferente', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
