# Generated by Django 5.2.8 on 2025-11-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(null=True),
        ),
    ]
