# Generated by Django 5.2.5 on 2025-11-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_email_alter_proveedor_sitio_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproveedor',
            name='min_lote',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='no-email@placeholder.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
